### ISSUE TITLE
Documentación inicial

### ISSUE THREAD

**Issue by cmoralesmx** [EricaConrad/Lista#1]
GUIs a crear:

CRUD de Profesor, sólo para 1 profesor, tiene que registrar sus datos al iniciar la app por primera vez y luego puede actualizarlos cuando quiera, no puede modificar su clave de profesor. La eliminación del profesor elimina también los datos de clases y grupos que tenga relacionados
CRUD de Grupos, N grupos (sólo captura el cuatrimestre, grupo y carrera 10A IFF)
CRUD de Materias, N materias (sólo captura nombre de la materia y clave, ej: ENS01 - Lenguage ensamblador 01)
CRUD de Alumnos, N alumnos (sólo capturará el nombre del alumno y su matrícula, ej: Kika Conrad - AAAA090909)
GUI de generación de reportes de asistencias

cada profesor tiene N grupos, cada grupo tiene N alumnos, cada grupo puede tener N materias

Para los horarios de clases relacionamos: profesor-grupo-materia asignando días y horas de clases, ejemplo:

prof01-grupo01-materia01, clases Lun 8-10, Mie 12-2, Vie 7-9

así cuando abra la app si está en horario de clase (o unos 10 minutos antes) debería mostrarle inmediatamente la GUI de pase de lista para el grupo inmediato

Tomando como referencia la hora actual, contra la hora de inicio de clase, puede asignar asistencia con una tolerancia de 10 minutos, 5 minutos más es retardo y el resto son faltas por default.

Reportes, se pueden generar:
En relación a un grupo: Por clase, por semana, mes o cuatrimestre
En relación a un alumno: por semana, mes o cuatrimestre

**Comment by EricaConrad** [comment]
vientos

2013/10/2 carlosmorales777 notifications@github.com

> GUIs a crear:
> 
> CRUD de Profesor, sólo para 1 profesor, tiene que registrar sus datos al
> iniciar la app por primera vez y luego puede actualizarlos cuando quiera,
> no puede modificar su clave de profesor. La eliminación del profesor
> elimina también los datos de clases y grupos que tenga relacionados
> CRUD de Grupos, N grupos (sólo captura el cuatrimestre, grupo y carrera
> 10A IFF)
> CRUD de Materias, N materias (sólo captura nombre de la materia y clave,
> ej: ENS01 - Lenguage ensamblador 01)
> CRUD de Alumnos, N alumnos (sólo capturará el nombre del alumno y su
> matrícula, ej: Kika Conrad - AAAA090909)
> GUI de generación de reportes de asistencias
> 
> cada profesor tiene N grupos, cada grupo tiene N alumnos, cada grupo puede
> tener N materias
> 
> Para los horarios de clases relacionamos: profesor-grupo-materia asignando
> días y horas de clases, ejemplo:
> 
> prof01-grupo01-materia01, clases Lun 8-10, Mie 12-2, Vie 7-9
> 
> así cuando abra la app si está en horario de clase (o unos 10 minutos
> antes) debería mostrarle inmediatamente la GUI de pase de lista para el
> grupo inmediato
> 
> Tomando como referencia la hora actual, contra la hora de inicio de clase,
> puede asignar asistencia con una tolerancia de 10 minutos, 5 minutos más es
> retardo y el resto son faltas por default.
> 
> Reportes, se pueden generar:
> En relación a un grupo: Por clase, por semana, mes o cuatrimestre
> En relación a un alumno: por semana, mes o cuatrimestre
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/EricaConrad/Lista/issues/1
> .

## 

Erica Conrad
